namespace Bluewater.Domain.Models.Groups;

public enum BluePermission
{
    AdminViewGroups = 1,
    AdminModifyGroups = 2,
    AdminViewSettings = 3,
    AdminModifySettings = 4,
    ViewProfiles = 5,
    AdminModifyUsers = 6,
    NewsView = 7,
    NewsModify = 8,
    NewsIconCreate = 9,
    NewsIconDelete = 10,
    AgendaModify = 11,
    AdminUsersView = 12,
    AdminUsersModify = 13,
    ExamsView = 14,
    ExamsModify = 15,
    ExamsAssign = 16,
    FleetView = 17,
    FleetModify = 18,
    ClustersView = 19,
    ClustersModify = 20,
    SignupView = 21,
    SignupRespond = 22,
    AdminSignupView = 23,
    AdminSignupModify = 24,
    AdminSignupModifyOthers = 25,
    OutingPlannerUse = 26,
}
